import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import FrontHome from "@/components/Home/FrontHome";
import SectionSide from "@/components/SectionSide/SectionSide";
import { CountApp, FavoriteColor } from "@/components/Home/ExcerciseState";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="max-w-[1512px] mx-auto">
          <div className="flex justify-center mt-20 space-x-5">
            <Link href="/framerMotion" className="p-4 border rounded-lg">
              Framer Motion
            </Link>
            <Link href="/framerMotion/scrollviewtext" className="p-4 border rounded-lg">
              View Text
            </Link>
            <Link href="/framerMotion/dynamiclist" className="p-4 border rounded-lg">
             Dynamic List View
            </Link>
            <Link href="/framerMotion/card" className="p-4 border rounded-lg">
             Crop Page
            </Link>
            <Link href="/framerMotion/mousecursor" className="p-4 border rounded-lg">
             Mousecursor
            </Link>
            <Link href="/carousel" className="p-4 border rounded-lg">
            Carousel
            </Link>
          </div>
          <FrontHome></FrontHome>
          <SectionSide></SectionSide>
          <FavoriteColor />
          <CountApp />
        </div>
      </main>
    </>
  );
}
